function result = calculate_process_zone_parameters( ...
        alpha, material, materialIndex, sigmaPrime, options)
%CALCULATE_PROCESS_ZONE_PARAMETERS Evaluate normalized Eqs. (8)-(10).
%
% The exponent lambda in these equations is the shear-cracked-corner root
% of D(-1-lambda)=0, not lambda1 or lambda2 from Figure 4.

if nargin < 5
    options = struct();
end
if ~isfield(options, 'root_options')
    options.root_options = struct();
end
if ~isfield(options, 'factor_options')
    options.factor_options = struct();
end
if materialIndex ~= 1 && materialIndex ~= 2
    error('characteristic_roots:InvalidMaterialIndex', ...
        'materialIndex must be 1 or 2.');
end

material = normalize_material(material);
roots = calculate_characteristic_roots( ...
    alpha, material, options.root_options);
coefficients = calculate_asymptotic_coefficients( ...
    alpha, material, roots, options.factor_options);

lambda = coefficients.lambda;
pLambda = coefficients.p_lambda;
kernelKind = sprintf('material%d', materialIndex);
processKernel = @(p) characteristic_kernel( ...
    kernelKind, p, alpha, material);
[processFactors, processDiagnostics] = wiener_hopf_plus_factor( ...
    processKernel, [pLambda, -1], options.factor_options);
GplusLambda = processFactors(1);
GplusMinus1 = processFactors(2);
Gi0 = characteristic_kernel(kernelKind, 0, alpha, material);

Kplus = @(p) gamma(1 - p) ./ gamma(0.5 - p);
Qprefactor = coefficients.Q_prefactor(materialIndex);
lengthBase = sigmaPrime .* Qprefactor .* Kplus(pLambda) ...
    .* GplusMinus1 ./ ((1 + lambda) .* Kplus(-1) .* GplusLambda);

negativeTolerance = 100 .* eps .* max(1, max(abs(lengthBase(:))));
shearProduct = sigmaPrime .* coefficients.g2;
shearTolerance = 100 .* eps .* max(1, max(abs(shearProduct(:))));
if any(lengthBase(:) < -negativeTolerance) ...
        || any(shearProduct(:) > shearTolerance)
    error('characteristic_roots:InadmissibleProcessZone', ...
        ['The load does not satisfy C*g2<0 and C*Q_i>0 for material %d. ', ...
        'Use the physically admissible sign of sigmaPrime.'], materialIndex);
end
lengthBase(abs(lengthBase) <= negativeTolerance) = 0;
dOverL = lengthBase .^ (-1 ./ lambda);

openingMultiplier = -lambda .* Kplus(-1) ./ ( ...
    sqrt(pi .* Gi0) .* (1 + lambda) .* GplusLambda);
energyMultiplier = -16 .* lambda ./ ( ...
    9 .* pi .* (lambda + 2) .* GplusMinus1.^2);

result = struct( ...
    'alpha_deg', alpha .* 180 ./ pi, ...
    'material_index', materialIndex, ...
    'sigma_prime', sigmaPrime, ...
    'd_over_l', dOverL, ...
    'delta_prime', openingMultiplier .* dOverL, ...
    'J_prime', energyMultiplier .* dOverL, ...
    'lambda', lambda, ...
    'Q_prefactor', Qprefactor, ...
    'Gi0', Gi0, ...
    'Gi_plus_lambda', GplusLambda, ...
    'Gi_plus_minus1', GplusMinus1, ...
    'opening_multiplier', openingMultiplier, ...
    'energy_multiplier', energyMultiplier, ...
    'roots', roots, ...
    'asymptotic_coefficients', coefficients, ...
    'factor_diagnostics', processDiagnostics);
end
