function coefficients = calculate_asymptotic_coefficients( ...
        alpha, material, roots, factorOptions)
%CALCULATE_ASYMPTOTIC_COEFFICIENTS Evaluate g1, S_i, q_i, and Q_i prefactors.
%
% Appendix A.3 gives Q_i = g1*q_i*l^(lambda0-lambda). This function returns
% g1*q_i as Q_prefactor; the normalized process-zone calculation absorbs
% the remaining l power into sigma' = C*l^lambda0/sigma_i.

if nargin < 3 || isempty(roots)
    roots = calculate_characteristic_roots(alpha, material);
end
if nargin < 4
    factorOptions = struct();
end
material = normalize_material(material);

lambda0 = roots.lambda0.selected;
lambda = roots.lambda.selected;
if ~isfinite(lambda0) || ~isfinite(lambda)
    error('characteristic_roots:MissingAsymptoticRoot', ...
        'lambda0 and lambda must be finite.');
end

pLambda = -1 - lambda;
pLambda0 = -1 - lambda0;
baseKernel = @(p) characteristic_kernel('base', p, alpha, material);
[baseFactors, baseDiagnostics] = wiener_hopf_plus_factor( ...
    baseKernel, [pLambda, pLambda0], factorOptions);

S1 = asymptotic_S(1, pLambda, alpha, material);
S2 = asymptotic_S(2, pLambda, alpha, material);
Dprime = characteristic_determinant_derivative( ...
    'D', pLambda, alpha, material);
Kplus = @(p) gamma(1 - p) ./ gamma(0.5 - p);

commonDenominator = (lambda - lambda0) .* Dprime ...
    .* Kplus(pLambda0) .* baseFactors(2);
q = 2 .* [S1, S2] .* Kplus(pLambda) .* baseFactors(1) ...
    ./ commonDenominator;

e = material.e;
k2 = material.kappa2;
g1 = (1 - e) .* sin(lambda0 .* (pi - alpha)) .* ( ...
    (lambda0 + 1) .* sin(2 .* alpha) ...
    + sin(2 .* (lambda0 + 1) .* alpha)) ...
    + e .* (1 + k2) .* sin(lambda0 .* pi) ...
    .* sin((lambda0 + 2) .* alpha);
g2 = (1 - e) .* cos(lambda0 .* (pi - alpha)) .* ( ...
    (lambda0 + 1) .* sin(2 .* alpha) ...
    + sin(2 .* (lambda0 + 1) .* alpha)) ...
    + e .* (1 + k2) .* sin(lambda0 .* pi) ...
    .* cos((lambda0 + 2) .* alpha);

coefficients = struct( ...
    'lambda0', lambda0, ...
    'lambda', lambda, ...
    'p_lambda', pLambda, ...
    'p_lambda0', pLambda0, ...
    'g1', g1, ...
    'g2', g2, ...
    'S1', S1, ...
    'S2', S2, ...
    'Dprime', Dprime, ...
    'base_Gplus_lambda', baseFactors(1), ...
    'base_Gplus_lambda0', baseFactors(2), ...
    'q1', q(1), ...
    'q2', q(2), ...
    'Q_prefactor', g1 .* q, ...
    'factor_diagnostics', baseDiagnostics);
end

function value = asymptotic_S(materialIndex, p, alpha, material)
e = material.e;
k1 = material.kappa1;
k2 = material.kappa2;
beta = pi - alpha;

if materialIndex == 1
    s11 = p .* cos(p .* pi - alpha) .* sin(alpha) ...
        - sin(p .* beta) .* cos(p .* alpha);
    s12 = p .* sin(2 .* alpha) + sin(2 .* p .* alpha);
    s13 = p .* cos(p .* beta) .* sin(alpha) ...
        - sin(p .* beta) .* cos(alpha);
    value = 2 .* e .* (1 + k2) .* s11 .* sin((p + 1) .* alpha) ...
        + s12 .* ((1 + k1) .* sin(p .* beta - alpha) ...
        + 2 .* (1 - e) .* s13);
elseif materialIndex == 2
    s21 = sin(2 .* p .* beta) - p .* sin(2 .* alpha);
    s22 = p .* cos(p .* alpha) .* sin(alpha) ...
        + sin(p .* alpha) .* cos(alpha);
    s23 = p .* cos(p .* pi + alpha) .* sin(alpha) ...
        + cos(p .* beta) .* sin(p .* alpha);
    value = s21 .* (e .* (1 + k2) .* sin((p + 1) .* alpha) ...
        + 2 .* (1 - e) .* s22) ...
        - 2 .* (1 + k1) .* sin(p .* beta - alpha) .* s23;
else
    error('characteristic_roots:InvalidMaterialIndex', ...
        'materialIndex must be 1 or 2.');
end
end
