function value = characteristic_determinant_derivative( ...
        kind, p, alpha, material)
%CHARACTERISTIC_DETERMINANT_DERIVATIVE Fourth-order numerical derivative.
%
% This is used for D'(-1-lambda) in Appendix A.3. The step size is chosen
% for double precision and the resulting derivative has a direct numerical
% checkpoint in the process-zone regression suite.

if any(~isreal(p(:)))
    error('characteristic_roots:ComplexDerivativePoint', ...
        'The current determinant derivative requires real p.');
end
h = 1e-4 .* (1 + abs(p));
value = ( ...
    characteristic_determinant(kind, p - 2 .* h, alpha, material) ...
    - 8 .* characteristic_determinant(kind, p - h, alpha, material) ...
    + 8 .* characteristic_determinant(kind, p + h, alpha, material) ...
    - characteristic_determinant(kind, p + 2 .* h, alpha, material)) ...
    ./ (12 .* h);
end
