function cases = figure2_case_definitions()
%FIGURE2_CASE_DEFINITIONS Baseline configurations plotted in Figure 2.
%
% The four cases are taken from the manuscript legend and the
% admissibility intervals in Section 3.  Green/blue encode C>0/C<0 and
% solid/dashed encode material 1/material 2, matching the original figure.

green = [0.10, 0.58, 0.25];
blue = [0.05, 0.38, 0.78];

cases = struct( ...
    'id', {'alpha10_material2', 'alpha45_material1', ...
        'alpha105_material2', 'alpha135_material1'}, ...
    'alpha_deg', {10, 45, 105, 135}, ...
    'material_index', {2, 1, 2, 1}, ...
    'sigma_min', {0, -0.5, -0.5, 0}, ...
    'sigma_max', {0.5, 0, 0, 0.5}, ...
    'line_style', {'--', '-', '--', '-'}, ...
    'color', {green, blue, blue, green}, ...
    'display_name', { ...
        '\alpha=10^{\circ}, \sigma^{\prime}>0, material 2', ...
        '\alpha=45^{\circ}, \sigma^{\prime}<0, material 1', ...
        '\alpha=105^{\circ}, \sigma^{\prime}<0, material 2', ...
        '\alpha=135^{\circ}, \sigma^{\prime}>0, material 1'});
end
