function cases = figure3_case_definitions()
%FIGURE3_CASE_DEFINITIONS Physical segments plotted in Figure 3.
%
% The order follows the manuscript legend. Green/blue encode C>0/C<0 and
% solid/dashed encode material 1/material 2.

green = [0.10, 0.58, 0.25];
blue = [0.05, 0.38, 0.78];

cases = struct( ...
    'id', {'C_positive_material2', 'C_negative_material1', ...
        'C_negative_material2', 'C_positive_material1'}, ...
    'material_index', {2, 1, 2, 1}, ...
    'sigma_prime', {0.5, -0.5, -0.5, 0.5}, ...
    'line_style', {'--', '-', '--', '-'}, ...
    'color', {green, blue, blue, green}, ...
    'display_name', { ...
        '\sigma^{\prime}=+0.5 (C>0), material 2', ...
        '\sigma^{\prime}=-0.5 (C<0), material 1', ...
        '\sigma^{\prime}=-0.5 (C<0), material 2', ...
        '\sigma^{\prime}=+0.5 (C>0), material 1'});
end
