function run_process_zone_tests()
%RUN_PROCESS_ZONE_TESTS Regression tests for all four Figure-2 cases.

material = struct('E1', 0.5, 'E2', 1.0, 'nu1', 0.3, 'nu2', 0.3);
alpha = deg2rad(45);
factorOptions = struct('truncation', 60, ...
    'relative_tolerance', 1e-10, 'absolute_tolerance', 1e-12);
options = struct('factor_options', factorOptions);

assert_close(characteristic_kernel('base', 0, alpha, material), ...
    0.823850242588080, 2e-10, 'G(0)');
assert_close(characteristic_kernel('material1', 0, alpha, material), ...
    1.04944322692827, 2e-10, 'G1(0)');
assert_close(characteristic_kernel('material2', 0, alpha, material), ...
    0.35991298904986, 2e-10, 'G2(0)');

% The corrected material-1 kernel must be the exact material-swap image of
% the printed material-2 kernel, including on the factorization contour.
swapped = swap_materials(material);
for p = [0, -0.4, 0.1i, 0.7i]
    direct = characteristic_kernel('material1', p, alpha, material);
    transformed = characteristic_kernel( ...
        'material2', p, pi - alpha, swapped);
    assert_close(direct, transformed, 2e-11, ...
        'material-1/material-2 kernel symmetry');
end

roots = calculate_characteristic_roots(alpha, material);
coefficients = calculate_asymptotic_coefficients( ...
    alpha, material, roots, factorOptions);
assert_close(coefficients.base_Gplus_lambda, ...
    0.986840102536902, 2e-7, 'G+(-1-lambda)');
assert_close(coefficients.base_Gplus_lambda0, ...
    1.00981779600980, 2e-7, 'G+(-1-lambda0)');
assert_close(coefficients.g1, -0.583869497507357, ...
    2e-10, 'g1');
assert_close(coefficients.g2, 0.902662692053291, ...
    2e-10, 'g2');
assert_close(coefficients.S1, 3.41146895580165, ...
    2e-9, 'S1(-1-lambda)');
assert_close(coefficients.Dprime, -17.0658334960677, ...
    2e-8, 'DPrime(-1-lambda)');
assert_close(coefficients.q1, 0.563193382302324, ...
    3e-7, 'q1');
assert(coefficients.Q_prefactor(1) < 0, ...
    'At 45 degrees Q1 must be negative.');
assert(coefficients.Q_prefactor(2) > 0, ...
    'At 45 degrees Q2 must be positive.');

result = calculate_process_zone_parameters( ...
    alpha, material, 1, [-0.1, -0.5], options);
assert_close(result.Gi_plus_lambda, 0.998663862614929, ...
    2e-7, 'G1+(-1-lambda)');
assert_close(result.Gi_plus_minus1, 0.996302154170794, ...
    2e-7, 'G1+(-1)');
assert_close(result.d_over_l(1), 0.010683677084003, ...
    2e-7, 'd1/l at sigmaPrime=-0.1');
assert_close(result.d_over_l(2), 0.147434361717898, ...
    2e-6, 'd1/l at sigmaPrime=-0.5');
assert_close(result.delta_prime(2), 0.145442265270518, ...
    2e-6, 'delta1Prime at sigmaPrime=-0.5');
assert_close(result.J_prime(2), 0.037164616543328, ...
    8e-7, 'J1Prime at sigmaPrime=-0.5');

expectedRatio = 5 .^ (-1 ./ result.lambda);
assert_close(result.d_over_l(2) ./ result.d_over_l(1), ...
    expectedRatio, 2e-10, 'load power-law scaling');
assert_close(result.delta_prime(2) ./ result.d_over_l(2), ...
    result.delta_prime(1) ./ result.d_over_l(1), ...
    2e-12, 'opening is proportional to zone length');
assert_close(result.J_prime(2) ./ result.d_over_l(2), ...
    result.J_prime(1) ./ result.d_over_l(1), ...
    2e-12, 'energy rate is proportional to zone length');

kernel1 = @(p) characteristic_kernel('material1', p, alpha, material);
factor20 = wiener_hopf_plus_factor(kernel1, [-1 - result.lambda, -1], ...
    struct('truncation', 20));
factor40 = wiener_hopf_plus_factor(kernel1, [-1 - result.lambda, -1], ...
    struct('truncation', 40));
assert(max(abs(factor20 - factor40)) < 2e-8, ...
    'Plus factors are not converged with respect to contour truncation.');

guardRaised = false;
try
    calculate_process_zone_parameters(alpha, material, 1, 0.5, options);
catch exception
    guardRaised = strcmp(exception.identifier, ...
        'characteristic_roots:InadmissibleProcessZone');
end
assert(guardRaised, ...
    'The inadmissible positive load for material 1 must be rejected.');

% The four definitions must reproduce the angles, materials, and load signs
% shown in the manuscript legend and selected by the admissibility rules.
cases = figure2_case_definitions();
assert(isequal([cases.alpha_deg], [10, 45, 105, 135]), ...
    'Unexpected Figure-2 angle definitions.');
assert(isequal([cases.material_index], [2, 1, 2, 1]), ...
    'Unexpected Figure-2 material definitions.');
assert(isequal([cases.sigma_min], [0, -0.5, -0.5, 0]) ...
        && isequal([cases.sigma_max], [0.5, 0, 0, 0.5]), ...
    'Unexpected Figure-2 load intervals.');
endpointSigma = [0.5, -0.5, -0.5, 0.5];
expectedLambda = [-0.871634481631286, -0.613197226573893, ...
    -0.261524697161322, -0.546757699994074];
expectedEndpoint = [ ...
    0.031324806384, 0.067772705874, 0.021725821310; ...
    0.147434361718, 0.145442265271, 0.037164616543; ...
    0.037035709254, 0.013442776906, 0.003922572967; ...
    0.051010519435, 0.057865884298, 0.013307413787];

for k = 1:numel(cases)
    alphaCase = deg2rad(cases(k).alpha_deg);
    sigmaPair = [endpointSigma(k) ./ 5, endpointSigma(k)];
    caseResult = calculate_process_zone_parameters( ...
        alphaCase, material, cases(k).material_index, sigmaPair, options);
    assert_close(caseResult.lambda, expectedLambda(k), 8e-9, ...
        sprintf('lambda at alpha=%g degrees', cases(k).alpha_deg));
    assert_close(caseResult.d_over_l(2), expectedEndpoint(k, 1), 3e-6, ...
        sprintf('d/l at alpha=%g degrees', cases(k).alpha_deg));
    assert_close(caseResult.delta_prime(2), expectedEndpoint(k, 2), ...
        3e-6, sprintf('deltaPrime at alpha=%g degrees', ...
        cases(k).alpha_deg));
    assert_close(caseResult.J_prime(2), expectedEndpoint(k, 3), 2e-6, ...
        sprintf('JPrime at alpha=%g degrees', cases(k).alpha_deg));

    expectedPowerRatio = 5 .^ (-1 ./ caseResult.lambda);
    assert_close(caseResult.d_over_l(2) ./ caseResult.d_over_l(1), ...
        expectedPowerRatio, 3e-10, sprintf( ...
        'load power law at alpha=%g degrees', cases(k).alpha_deg));
    assert_close(caseResult.delta_prime(2) ./ caseResult.d_over_l(2), ...
        caseResult.delta_prime(1) ./ caseResult.d_over_l(1), 2e-12, ...
        sprintf('opening proportionality at alpha=%g degrees', ...
        cases(k).alpha_deg));
    assert_close(caseResult.J_prime(2) ./ caseResult.d_over_l(2), ...
        caseResult.J_prime(1) ./ caseResult.d_over_l(1), 2e-12, ...
        sprintf('energy proportionality at alpha=%g degrees', ...
        cases(k).alpha_deg));

    guardRaised = false;
    try
        calculate_process_zone_parameters(alphaCase, material, ...
            cases(k).material_index, -endpointSigma(k), options);
    catch exception
        guardRaised = strcmp(exception.identifier, ...
            'characteristic_roots:InadmissibleProcessZone');
    end
    assert(guardRaised, sprintf( ...
        'The opposite load sign at alpha=%g degrees must be rejected.', ...
        cases(k).alpha_deg));
end

% The 10-degree kernels approach one more slowly than the other cases.
% Truncation 60 is therefore used for Figure 2 and compared against 40.
alpha10 = deg2rad(10);
roots10 = calculate_characteristic_roots(alpha10, material);
p10 = -1 - roots10.lambda.selected;
base10 = @(p) characteristic_kernel('base', p, alpha10, material);
kernel10 = @(p) characteristic_kernel('material2', p, alpha10, material);
base40 = wiener_hopf_plus_factor(base10, ...
    [p10, -1 - roots10.lambda0.selected], struct('truncation', 40));
base60 = wiener_hopf_plus_factor(base10, ...
    [p10, -1 - roots10.lambda0.selected], struct('truncation', 60));
process40 = wiener_hopf_plus_factor(kernel10, [p10, -1], ...
    struct('truncation', 40));
process60 = wiener_hopf_plus_factor(kernel10, [p10, -1], ...
    struct('truncation', 60));
assert(max(abs(base40 - base60)) < 1e-6, ...
    'The 10-degree base plus factors are not truncation-converged.');
assert(max(abs(process40 - process60)) < 1e-6, ...
    'The 10-degree material-2 plus factors are not truncation-converged.');

fprintf('All Figure-2 process-zone tests passed.\n');
end

function assert_close(actual, expected, tolerance, label)
if any(~isfinite(actual(:))) || any(abs(actual(:) - expected) > tolerance)
    error('characteristic_roots:RegressionFailure', ...
        '%s: expected %.15g, obtained %.15g.', label, expected, actual);
end
end
