function swapped = swap_materials(material)
%SWAP_MATERIALS Exchange material labels 1 and 2.

material = normalize_material(material);
swapped = struct( ...
    'E1', material.E2, ...
    'E2', material.E1, ...
    'nu1', material.nu2, ...
    'nu2', material.nu1);
swapped = normalize_material(swapped);
end
